import type { ProductCardProps } from "@/src/components/product/ProductCard";

// ─── Types ────────────────────────────────────────────────────────────────────

export type DealCategory =
  | "laptop"
  | "cpu"
  | "gpu"
  | "ram"
  | "ssd"
  | "monitor"
  | "keyboard"
  | "mouse";

export interface DealCategoryMeta {
  value: DealCategory;
  label: string;
}

export interface FlashSaleEvent {
  /** ISO date string — when the flash sale ends */
  endsAt: string;
  label: string;
  products: ProductCardProps[];
}

export interface DealGroup {
  category: DealCategory;
  products: ProductCardProps[];
}

// ─── Category metadata ────────────────────────────────────────────────────────

export const DEAL_CATEGORY_META: DealCategoryMeta[] = [
  { value: "laptop",   label: "Laptop Gaming" },
  { value: "cpu",      label: "CPU" },
  { value: "gpu",      label: "GPU" },
  { value: "ram",      label: "RAM" },
  { value: "ssd",      label: "SSD" },
  { value: "monitor",  label: "Màn hình" },
  { value: "keyboard", label: "Bàn phím" },
  { value: "mouse",    label: "Chuột" },
];

// ─── Flash sale ───────────────────────────────────────────────────────────────
// endsAt = ~23h 47m from module evaluation time.

export const FLASH_SALE: FlashSaleEvent = {
  endsAt: new Date(Date.now() + 23 * 60 * 60 * 1000 + 47 * 60 * 1000).toISOString(),
  label: "Flash Sale Hôm Nay",
  products: [
    {
      id: "flash-rtx4070-super-tuf",
      name: "VGA Asus TUF Gaming GeForce RTX 4070 SUPER OC 12GB GDDR6X",
      brand: "ASUS",
      href: "/products/rtx4070-super-tuf",
      thumbnail: "/icons/gpu.png",
      badge: "Flash Sale",
      productCode: "GPU03001",
      price: 17_990_000,
      originalPrice: 23_500_000,
      rating: 4.9,
      reviewCount: 214,
      stockStatus: "low-stock",
      stockQuantity: 5,
    },
    {
      id: "flash-i5-14600k",
      name: "CPU Intel Core i5-14600K (3.5GHz turbo 5.3GHz, 14 nhân 20 luồng, 24MB Cache)",
      brand: "Intel",
      href: "/products/i5-14600k",
      thumbnail: "/icons/cpu.png",
      badge: "Flash Sale",
      productCode: "CPU02005",
      price: 6_490_000,
      originalPrice: 8_200_000,
      rating: 4.8,
      reviewCount: 178,
      stockStatus: "low-stock",
      stockQuantity: 8,
    },
    {
      id: "flash-fury-beast-ddr5-32",
      name: "RAM Kingston Fury Beast DDR5 32GB (2x16GB) 6000MHz CL36 RGB",
      brand: "Kingston",
      href: "/products/fury-beast-ddr5-32",
      thumbnail: "/icons/ram.png",
      badge: "Flash Sale",
      productCode: "RAM04003",
      price: 2_490_000,
      originalPrice: 3_200_000,
      rating: 4.7,
      reviewCount: 93,
      stockStatus: "low-stock",
      stockQuantity: 12,
    },
    {
      id: "flash-samsung-990-pro-2tb",
      name: "SSD Samsung 990 Pro 2TB NVMe PCIe 4.0 M.2 (7450/6900 MB/s)",
      brand: "Samsung",
      href: "/products/samsung-990-pro-2tb",
      thumbnail: "/icons/ssd.png",
      badge: "Flash Sale",
      productCode: "SSD05002",
      price: 3_490_000,
      originalPrice: 4_500_000,
      rating: 4.9,
      reviewCount: 312,
      stockStatus: "low-stock",
      stockQuantity: 7,
    },
    {
      id: "flash-keychron-k2-pro",
      name: "Bàn phím Keychron K2 Pro QMK/VIA Wireless Mechanical (Gateron Red)",
      brand: "Keychron",
      href: "/products/keychron-k2-pro",
      thumbnail: "/icons/keyboard.png",
      badge: "Flash Sale",
      productCode: "KB06001",
      price: 1_890_000,
      originalPrice: 2_490_000,
      rating: 4.8,
      reviewCount: 147,
      stockStatus: "low-stock",
      stockQuantity: 15,
    },
    {
      id: "flash-g-pro-x-superlight2",
      name: "Chuột Logitech G Pro X Superlight 2 Wireless Gaming (25600 DPI, 60g)",
      brand: "Logitech",
      href: "/products/g-pro-x-superlight2",
      thumbnail: "/icons/mouse.png",
      badge: "Flash Sale",
      productCode: "MS07001",
      price: 2_790_000,
      originalPrice: 3_590_000,
      rating: 4.9,
      reviewCount: 268,
      stockStatus: "low-stock",
      stockQuantity: 9,
    },
  ],
};

// ─── Deal groups by category ──────────────────────────────────────────────────

export const DEAL_GROUPS: DealGroup[] = [
  // ── Laptop Gaming ────────────────────────────────────────────────────────────
  {
    category: "laptop",
    products: [
      {
        id: "deal-rog-strix-g16-2024",
        name: "Laptop Asus ROG Strix G16 G614JZR (Intel Core i9-14900HX/32GB/1TB/RTX 4080 12GB/16\" QHD 240Hz/Win11)",
        brand: "ASUS",
        href: "/products/rog-strix-g16-2024",
        thumbnail: "/icons/laptop-gaming.png",
        badge: "Sale",
        productCode: "LG01001",
        price: 54_990_000,
        originalPrice: 65_000_000,
        rating: 4.9,
        reviewCount: 124,
        stockStatus: "in-stock",
      },
      {
        id: "deal-msi-titan-gt77",
        name: "Laptop MSI Titan GT77 HX (Intel Core i9-13980HX/64GB/2TB/RTX 4090 16GB/17.3\" UHD 144Hz)",
        brand: "MSI",
        href: "/products/msi-titan-gt77",
        thumbnail: "/icons/laptop-gaming.png",
        badge: "Sale",
        productCode: "LG01002",
        price: 89_990_000,
        originalPrice: 109_000_000,
        rating: 4.8,
        reviewCount: 56,
        stockStatus: "low-stock",
        stockQuantity: 3,
      },
      {
        id: "deal-legion-7i-gen9",
        name: "Laptop Lenovo Legion 7i Gen 9 (Intel Core Ultra 9 185HX/32GB/1TB/RTX 4070 8GB/16\" WQXGA 165Hz)",
        brand: "Lenovo",
        href: "/products/legion-7i-gen9",
        thumbnail: "/icons/laptop-gaming.png",
        badge: "Sale",
        productCode: "LG01003",
        price: 47_490_000,
        originalPrice: 56_000_000,
        rating: 4.7,
        reviewCount: 89,
        stockStatus: "in-stock",
      },
      {
        id: "deal-acer-predator-helios-neo16",
        name: "Laptop Acer Predator Helios Neo 16 (Intel Core i7-14650HX/16GB/512GB/RTX 4060 8GB/16\" WUXGA 165Hz)",
        brand: "Acer",
        href: "/products/predator-helios-neo16",
        thumbnail: "/icons/laptop-gaming.png",
        badge: "Sale",
        productCode: "LG01004",
        price: 28_490_000,
        originalPrice: 33_500_000,
        rating: 4.6,
        reviewCount: 112,
        stockStatus: "in-stock",
      },
      {
        id: "deal-hp-omen-16-2024",
        name: "Laptop HP Omen 16 (AMD Ryzen 7 8745H/16GB/1TB/RTX 4060 8GB/16.1\" FHD 165Hz/Win11)",
        brand: "HP",
        href: "/products/hp-omen-16-2024",
        thumbnail: "/icons/laptop-gaming.png",
        badge: "Sale",
        productCode: "LG01005",
        price: 32_990_000,
        originalPrice: 39_000_000,
        rating: 4.6,
        reviewCount: 77,
        stockStatus: "in-stock",
      },
      {
        id: "deal-aorus-15-bxf",
        name: "Laptop Gigabyte Aorus 15 BXF (Intel Core i7-13700H/16GB/512GB/RTX 4070 8GB/15.6\" FHD 360Hz)",
        brand: "Gigabyte",
        href: "/products/aorus-15-bxf",
        thumbnail: "/icons/laptop-gaming.png",
        badge: "Sale",
        productCode: "LG01006",
        price: 35_490_000,
        originalPrice: 42_000_000,
        rating: 4.7,
        reviewCount: 63,
        stockStatus: "in-stock",
      },
    ],
  },

  // ── CPU ───────────────────────────────────────────────────────────────────────
  {
    category: "cpu",
    products: [
      {
        id: "deal-i9-14900k",
        name: "CPU Intel Core i9-14900K (3.2GHz turbo 6.0GHz, 24 nhân 32 luồng, 36MB Cache, Socket LGA1700)",
        brand: "Intel",
        href: "/products/i9-14900k",
        thumbnail: "/icons/cpu.png",
        badge: "Sale",
        productCode: "CPU02001",
        price: 11_490_000,
        originalPrice: 14_500_000,
        rating: 4.9,
        reviewCount: 203,
        stockStatus: "in-stock",
      },
      {
        id: "deal-i7-14700k",
        name: "CPU Intel Core i7-14700K (3.4GHz turbo 5.6GHz, 20 nhân 28 luồng, 33MB Cache, Socket LGA1700)",
        brand: "Intel",
        href: "/products/i7-14700k",
        thumbnail: "/icons/cpu.png",
        badge: "Sale",
        productCode: "CPU02002",
        price: 8_490_000,
        originalPrice: 10_200_000,
        rating: 4.8,
        reviewCount: 156,
        stockStatus: "in-stock",
      },
      {
        id: "deal-i5-14600k",
        name: "CPU Intel Core i5-14600K (3.5GHz turbo 5.3GHz, 14 nhân 20 luồng, 24MB Cache, Socket LGA1700)",
        brand: "Intel",
        href: "/products/i5-14600k",
        thumbnail: "/icons/cpu.png",
        badge: "Sale",
        productCode: "CPU02003",
        price: 6_790_000,
        originalPrice: 8_200_000,
        rating: 4.8,
        reviewCount: 289,
        stockStatus: "in-stock",
      },
      {
        id: "deal-ryzen9-7950x",
        name: "CPU AMD Ryzen 9 7950X (4.5GHz turbo 5.7GHz, 16 nhân 32 luồng, 64MB Cache, Socket AM5)",
        brand: "AMD",
        href: "/products/ryzen9-7950x",
        thumbnail: "/icons/cpu.png",
        badge: "Sale",
        productCode: "CPU02004",
        price: 13_990_000,
        originalPrice: 17_500_000,
        rating: 4.9,
        reviewCount: 118,
        stockStatus: "in-stock",
      },
      {
        id: "deal-ryzen7-7800x3d",
        name: "CPU AMD Ryzen 7 7800X3D (4.5GHz turbo 5.0GHz, 8 nhân 16 luồng, 96MB Cache 3D V-Cache, AM5)",
        brand: "AMD",
        href: "/products/ryzen7-7800x3d",
        thumbnail: "/icons/cpu.png",
        badge: "Sale",
        productCode: "CPU02005",
        price: 9_490_000,
        originalPrice: 11_500_000,
        rating: 4.9,
        reviewCount: 342,
        stockStatus: "low-stock",
        stockQuantity: 6,
      },
      {
        id: "deal-ryzen5-7600x",
        name: "CPU AMD Ryzen 5 7600X (4.7GHz turbo 5.3GHz, 6 nhân 12 luồng, 32MB Cache, Socket AM5)",
        brand: "AMD",
        href: "/products/ryzen5-7600x",
        thumbnail: "/icons/cpu.png",
        badge: "Sale",
        productCode: "CPU02006",
        price: 4_990_000,
        originalPrice: 6_200_000,
        rating: 4.7,
        reviewCount: 197,
        stockStatus: "in-stock",
      },
    ],
  },

  // ── GPU ───────────────────────────────────────────────────────────────────────
  {
    category: "gpu",
    products: [
      {
        id: "deal-rtx4080-super-tuf",
        name: "VGA Asus TUF Gaming GeForce RTX 4080 SUPER OC 16GB GDDR6X",
        brand: "ASUS",
        href: "/products/rtx4080-super-tuf",
        thumbnail: "/icons/gpu.png",
        badge: "Sale",
        productCode: "GPU03002",
        price: 29_990_000,
        originalPrice: 37_500_000,
        rating: 4.9,
        reviewCount: 87,
        stockStatus: "in-stock",
      },
      {
        id: "deal-rtx4070ti-super-msi",
        name: "VGA MSI Gaming X Slim GeForce RTX 4070 Ti SUPER 16GB GDDR6X",
        brand: "MSI",
        href: "/products/rtx4070ti-super-msi",
        thumbnail: "/icons/gpu.png",
        badge: "Sale",
        productCode: "GPU03003",
        price: 24_490_000,
        originalPrice: 29_900_000,
        rating: 4.8,
        reviewCount: 134,
        stockStatus: "in-stock",
      },
      {
        id: "deal-rx7900xt-gigabyte",
        name: "VGA Gigabyte Radeon RX 7900 XT Gaming OC 20GB GDDR6",
        brand: "Gigabyte",
        href: "/products/rx7900xt-gigabyte",
        thumbnail: "/icons/gpu.png",
        badge: "Sale",
        productCode: "GPU03004",
        price: 21_990_000,
        originalPrice: 26_500_000,
        rating: 4.7,
        reviewCount: 69,
        stockStatus: "in-stock",
      },
      {
        id: "deal-rx7800xt-sapphire",
        name: "VGA Sapphire Pulse Radeon RX 7800 XT 16GB GDDR6",
        brand: "Sapphire",
        href: "/products/rx7800xt-sapphire",
        thumbnail: "/icons/gpu.png",
        badge: "Sale",
        productCode: "GPU03005",
        price: 12_490_000,
        originalPrice: 15_200_000,
        rating: 4.7,
        reviewCount: 103,
        stockStatus: "in-stock",
      },
      {
        id: "deal-rtx4060ti-zotac",
        name: "VGA Zotac Gaming GeForce RTX 4060 Ti 16GB GDDR6",
        brand: "Zotac",
        href: "/products/rtx4060ti-zotac",
        thumbnail: "/icons/gpu.png",
        badge: "Sale",
        productCode: "GPU03006",
        price: 9_490_000,
        originalPrice: 11_500_000,
        rating: 4.6,
        reviewCount: 145,
        stockStatus: "in-stock",
      },
      {
        id: "deal-rtx4060-asus-dual",
        name: "VGA Asus Dual GeForce RTX 4060 OC 8GB GDDR6",
        brand: "ASUS",
        href: "/products/rtx4060-asus-dual",
        thumbnail: "/icons/gpu.png",
        badge: "Sale",
        productCode: "GPU03007",
        price: 7_490_000,
        originalPrice: 9_200_000,
        rating: 4.6,
        reviewCount: 218,
        stockStatus: "in-stock",
      },
    ],
  },

  // ── RAM ───────────────────────────────────────────────────────────────────────
  {
    category: "ram",
    products: [
      {
        id: "deal-corsair-vengeance-ddr5-64",
        name: "RAM Corsair Vengeance RGB DDR5 64GB (2x32GB) 6400MHz CL32 (CMH64GX5M2B6400C32)",
        brand: "Corsair",
        href: "/products/corsair-vengeance-ddr5-64",
        thumbnail: "/icons/ram.png",
        badge: "Sale",
        productCode: "RAM04001",
        price: 4_290_000,
        originalPrice: 5_500_000,
        rating: 4.8,
        reviewCount: 74,
        stockStatus: "in-stock",
      },
      {
        id: "deal-gskill-tridentz5-ddr5-32",
        name: "RAM G.Skill Trident Z5 RGB DDR5 32GB (2x16GB) 7200MHz CL34",
        brand: "G.Skill",
        href: "/products/gskill-tridentz5-ddr5-32",
        thumbnail: "/icons/ram.png",
        badge: "Sale",
        productCode: "RAM04002",
        price: 3_190_000,
        originalPrice: 3_990_000,
        rating: 4.8,
        reviewCount: 91,
        stockStatus: "in-stock",
      },
      {
        id: "deal-kingston-fury-renegade-ddr5-32",
        name: "RAM Kingston Fury Renegade DDR5 32GB (2x16GB) 6400MHz CL32 RGB",
        brand: "Kingston",
        href: "/products/fury-renegade-ddr5-32",
        thumbnail: "/icons/ram.png",
        badge: "Sale",
        productCode: "RAM04003",
        price: 2_790_000,
        originalPrice: 3_400_000,
        rating: 4.7,
        reviewCount: 108,
        stockStatus: "in-stock",
      },
      {
        id: "deal-gskill-ripjaws-ddr4-32",
        name: "RAM G.Skill Ripjaws V DDR4 32GB (2x16GB) 3600MHz CL18",
        brand: "G.Skill",
        href: "/products/gskill-ripjaws-ddr4-32",
        thumbnail: "/icons/ram.png",
        badge: "Sale",
        productCode: "RAM04004",
        price: 1_390_000,
        originalPrice: 1_750_000,
        rating: 4.7,
        reviewCount: 234,
        stockStatus: "in-stock",
      },
      {
        id: "deal-corsair-lpx-ddr4-16",
        name: "RAM Corsair Vengeance LPX DDR4 16GB (2x8GB) 3200MHz CL16",
        brand: "Corsair",
        href: "/products/corsair-lpx-ddr4-16",
        thumbnail: "/icons/ram.png",
        badge: "Sale",
        productCode: "RAM04005",
        price: 790_000,
        originalPrice: 990_000,
        rating: 4.6,
        reviewCount: 312,
        stockStatus: "in-stock",
      },
      {
        id: "deal-kingston-fury-beast-ddr4-32",
        name: "RAM Kingston Fury Beast DDR4 32GB (2x16GB) 3600MHz CL18 RGB",
        brand: "Kingston",
        href: "/products/fury-beast-ddr4-32",
        thumbnail: "/icons/ram.png",
        badge: "Sale",
        productCode: "RAM04006",
        price: 1_490_000,
        originalPrice: 1_890_000,
        rating: 4.7,
        reviewCount: 156,
        stockStatus: "in-stock",
      },
    ],
  },

  // ── SSD ───────────────────────────────────────────────────────────────────────
  {
    category: "ssd",
    products: [
      {
        id: "deal-samsung-990-pro-2tb",
        name: "SSD Samsung 990 Pro 2TB NVMe PCIe 4.0 M.2 (7450/6900 MB/s, DRAM Cache)",
        brand: "Samsung",
        href: "/products/samsung-990-pro-2tb",
        thumbnail: "/icons/ssd.png",
        badge: "Sale",
        productCode: "SSD05001",
        price: 3_690_000,
        originalPrice: 4_800_000,
        rating: 4.9,
        reviewCount: 287,
        stockStatus: "in-stock",
      },
      {
        id: "deal-wd-black-sn850x-2tb",
        name: "SSD WD Black SN850X 2TB NVMe PCIe 4.0 M.2 (7300/6600 MB/s, DRAM Cache)",
        brand: "WD",
        href: "/products/wd-black-sn850x-2tb",
        thumbnail: "/icons/ssd.png",
        badge: "Sale",
        productCode: "SSD05002",
        price: 3_290_000,
        originalPrice: 4_200_000,
        rating: 4.8,
        reviewCount: 192,
        stockStatus: "in-stock",
      },
      {
        id: "deal-seagate-firecuda-530-2tb",
        name: "SSD Seagate FireCuda 530 2TB NVMe PCIe 4.0 M.2 (7300/6900 MB/s)",
        brand: "Seagate",
        href: "/products/seagate-firecuda-530-2tb",
        thumbnail: "/icons/ssd.png",
        badge: "Sale",
        productCode: "SSD05003",
        price: 2_990_000,
        originalPrice: 3_800_000,
        rating: 4.7,
        reviewCount: 134,
        stockStatus: "in-stock",
      },
      {
        id: "deal-kingston-fury-renegade-1tb",
        name: "SSD Kingston Fury Renegade 1TB NVMe PCIe 4.0 M.2 (7300/6000 MB/s)",
        brand: "Kingston",
        href: "/products/kingston-fury-renegade-1tb",
        thumbnail: "/icons/ssd.png",
        badge: "Sale",
        productCode: "SSD05004",
        price: 1_690_000,
        originalPrice: 2_100_000,
        rating: 4.8,
        reviewCount: 211,
        stockStatus: "in-stock",
      },
      {
        id: "deal-samsung-870-evo-1tb",
        name: "SSD Samsung 870 EVO 1TB SATA III 2.5\" (560/530 MB/s, DRAM Cache)",
        brand: "Samsung",
        href: "/products/samsung-870-evo-1tb",
        thumbnail: "/icons/ssd.png",
        badge: "Sale",
        productCode: "SSD05005",
        price: 1_290_000,
        originalPrice: 1_590_000,
        rating: 4.8,
        reviewCount: 403,
        stockStatus: "in-stock",
      },
      {
        id: "deal-wd-blue-sn580-1tb",
        name: "SSD WD Blue SN580 1TB NVMe PCIe 4.0 M.2 (4150/4150 MB/s)",
        brand: "WD",
        href: "/products/wd-blue-sn580-1tb",
        thumbnail: "/icons/ssd.png",
        badge: "Sale",
        productCode: "SSD05006",
        price: 1_090_000,
        originalPrice: 1_390_000,
        rating: 4.6,
        reviewCount: 278,
        stockStatus: "in-stock",
      },
    ],
  },

  // ── Monitor ───────────────────────────────────────────────────────────────────
  {
    category: "monitor",
    products: [
      {
        id: "deal-lg-ultragear-27gp850",
        name: "Màn hình LG UltraGear 27GP850-B 27\" QHD IPS 165Hz 1ms G-Sync Compatible",
        brand: "LG",
        href: "/products/lg-ultragear-27gp850",
        thumbnail: "/icons/monitor.png",
        badge: "Sale",
        productCode: "MN08001",
        price: 7_490_000,
        originalPrice: 9_500_000,
        rating: 4.8,
        reviewCount: 189,
        stockStatus: "in-stock",
      },
      {
        id: "deal-samsung-odyssey-g7-32",
        name: "Màn hình Samsung Odyssey G7 32\" QHD VA 240Hz 1ms HDR600 Cong",
        brand: "Samsung",
        href: "/products/samsung-odyssey-g7-32",
        thumbnail: "/icons/monitor.png",
        badge: "Sale",
        productCode: "MN08002",
        price: 10_990_000,
        originalPrice: 14_000_000,
        rating: 4.7,
        reviewCount: 113,
        stockStatus: "in-stock",
      },
      {
        id: "deal-asus-rog-swift-pg279qm",
        name: "Màn hình Asus ROG Swift PG279QM 27\" QHD IPS 240Hz 1ms G-Sync",
        brand: "ASUS",
        href: "/products/asus-rog-swift-pg279qm",
        thumbnail: "/icons/monitor.png",
        badge: "Sale",
        productCode: "MN08003",
        price: 14_490_000,
        originalPrice: 18_500_000,
        rating: 4.8,
        reviewCount: 78,
        stockStatus: "low-stock",
        stockQuantity: 4,
      },
      {
        id: "deal-benq-mobiuz-ex2710q",
        name: "Màn hình BenQ Mobiuz EX2710Q 27\" QHD IPS 165Hz 1ms HDR400 FreeSync",
        brand: "BenQ",
        href: "/products/benq-mobiuz-ex2710q",
        thumbnail: "/icons/monitor.png",
        badge: "Sale",
        productCode: "MN08004",
        price: 7_990_000,
        originalPrice: 9_900_000,
        rating: 4.7,
        reviewCount: 142,
        stockStatus: "in-stock",
      },
      {
        id: "deal-acer-nitro-xv272u",
        name: "Màn hình Acer Nitro XV272U KVbmiiprzx 27\" QHD IPS 170Hz 1ms FreeSync Premium",
        brand: "Acer",
        href: "/products/acer-nitro-xv272u",
        thumbnail: "/icons/monitor.png",
        badge: "Sale",
        productCode: "MN08005",
        price: 6_490_000,
        originalPrice: 7_900_000,
        rating: 4.6,
        reviewCount: 97,
        stockStatus: "in-stock",
      },
      {
        id: "deal-aoc-27g2zu",
        name: "Màn hình AOC 27G2ZU/BK 27\" FHD IPS 240Hz 0.5ms G-Sync Compatible",
        brand: "AOC",
        href: "/products/aoc-27g2zu",
        thumbnail: "/icons/monitor.png",
        badge: "Sale",
        productCode: "MN08006",
        price: 5_490_000,
        originalPrice: 6_800_000,
        rating: 4.5,
        reviewCount: 163,
        stockStatus: "in-stock",
      },
    ],
  },

  // ── Keyboard ──────────────────────────────────────────────────────────────────
  {
    category: "keyboard",
    products: [
      {
        id: "deal-keychron-k2-pro",
        name: "Bàn phím Keychron K2 Pro QMK/VIA Wireless Mechanical RGB Hotswap (Gateron G Pro Red)",
        brand: "Keychron",
        href: "/products/keychron-k2-pro",
        thumbnail: "/icons/keyboard.png",
        badge: "Sale",
        productCode: "KB06001",
        price: 2_090_000,
        originalPrice: 2_590_000,
        rating: 4.8,
        reviewCount: 147,
        stockStatus: "in-stock",
      },
      {
        id: "deal-corsair-k100-rgb",
        name: "Bàn phím Corsair K100 RGB Mechanical Gaming (Cherry MX Speed Silver, Per-Key RGB)",
        brand: "Corsair",
        href: "/products/corsair-k100-rgb",
        thumbnail: "/icons/keyboard.png",
        badge: "Sale",
        productCode: "KB06002",
        price: 4_290_000,
        originalPrice: 5_500_000,
        rating: 4.7,
        reviewCount: 89,
        stockStatus: "in-stock",
      },
      {
        id: "deal-steelseries-apex-pro-tkl",
        name: "Bàn phím SteelSeries Apex Pro TKL Wireless (OmniPoint 2.0 Adjustable, OLED Display)",
        brand: "SteelSeries",
        href: "/products/steelseries-apex-pro-tkl",
        thumbnail: "/icons/keyboard.png",
        badge: "Sale",
        productCode: "KB06003",
        price: 3_890_000,
        originalPrice: 4_900_000,
        rating: 4.8,
        reviewCount: 113,
        stockStatus: "in-stock",
      },
      {
        id: "deal-asus-rog-strix-scope-rx",
        name: "Bàn phím Asus ROG Strix Scope RX TKL Wireless Deluxe (ROG RX Red Switch, RGB)",
        brand: "ASUS",
        href: "/products/asus-rog-strix-scope-rx",
        thumbnail: "/icons/keyboard.png",
        badge: "Sale",
        productCode: "KB06004",
        price: 2_890_000,
        originalPrice: 3_600_000,
        rating: 4.7,
        reviewCount: 76,
        stockStatus: "in-stock",
      },
      {
        id: "deal-razer-blackwidow-v4",
        name: "Bàn phím Razer BlackWidow V4 Pro Mechanical (Yellow Switch, Doubleshot ABS, Chroma RGB)",
        brand: "Razer",
        href: "/products/razer-blackwidow-v4",
        thumbnail: "/icons/keyboard.png",
        badge: "Sale",
        productCode: "KB06005",
        price: 3_490_000,
        originalPrice: 4_290_000,
        rating: 4.6,
        reviewCount: 94,
        stockStatus: "in-stock",
      },
      {
        id: "deal-hyperx-alloy-origins-65",
        name: "Bàn phím HyperX Alloy Origins 65 Mechanical Gaming (HyperX Red Linear, RGB, Compact)",
        brand: "HyperX",
        href: "/products/hyperx-alloy-origins-65",
        thumbnail: "/icons/keyboard.png",
        badge: "Sale",
        productCode: "KB06006",
        price: 1_690_000,
        originalPrice: 2_190_000,
        rating: 4.5,
        reviewCount: 138,
        stockStatus: "in-stock",
      },
    ],
  },

  // ── Mouse ─────────────────────────────────────────────────────────────────────
  {
    category: "mouse",
    products: [
      {
        id: "deal-g-pro-x-superlight2",
        name: "Chuột Logitech G Pro X Superlight 2 Wireless Gaming (HERO 25K, 60g, USB-C)",
        brand: "Logitech",
        href: "/products/g-pro-x-superlight2",
        thumbnail: "/icons/mouse.png",
        badge: "Sale",
        productCode: "MS07001",
        price: 2_990_000,
        originalPrice: 3_790_000,
        rating: 4.9,
        reviewCount: 268,
        stockStatus: "in-stock",
      },
      {
        id: "deal-razer-deathadder-v3-pro",
        name: "Chuột Razer DeathAdder V3 Pro Wireless Gaming (Focus Pro 30K, 63g, HyperSpeed)",
        brand: "Razer",
        href: "/products/razer-deathadder-v3-pro",
        thumbnail: "/icons/mouse.png",
        badge: "Sale",
        productCode: "MS07002",
        price: 2_690_000,
        originalPrice: 3_390_000,
        rating: 4.8,
        reviewCount: 187,
        stockStatus: "in-stock",
      },
      {
        id: "deal-steelseries-prime-mini-wireless",
        name: "Chuột SteelSeries Prime Mini Wireless Gaming (TrueMove Air 18K, 57g)",
        brand: "SteelSeries",
        href: "/products/steelseries-prime-mini-wireless",
        thumbnail: "/icons/mouse.png",
        badge: "Sale",
        productCode: "MS07003",
        price: 1_790_000,
        originalPrice: 2_290_000,
        rating: 4.7,
        reviewCount: 134,
        stockStatus: "in-stock",
      },
      {
        id: "deal-zowie-ec2-c",
        name: "Chuột Zowie EC2-C Gaming (3360 Sensor, 70g, Symmetric, USB-C, No Driver)",
        brand: "Zowie",
        href: "/products/zowie-ec2-c",
        thumbnail: "/icons/mouse.png",
        badge: "Sale",
        productCode: "MS07004",
        price: 1_390_000,
        originalPrice: 1_690_000,
        rating: 4.7,
        reviewCount: 156,
        stockStatus: "in-stock",
      },
      {
        id: "deal-logitech-g502x-plus",
        name: "Chuột Logitech G502 X Plus Wireless Gaming (HERO 25K, 106g, LIGHTSYNC RGB)",
        brand: "Logitech",
        href: "/products/logitech-g502x-plus",
        thumbnail: "/icons/mouse.png",
        badge: "Sale",
        productCode: "MS07005",
        price: 2_090_000,
        originalPrice: 2_690_000,
        rating: 4.7,
        reviewCount: 203,
        stockStatus: "in-stock",
      },
      {
        id: "deal-hyperx-pulsefire-haste2",
        name: "Chuột HyperX Pulsefire Haste 2 Wireless Gaming (26K DPI, 53g, USB-C)",
        brand: "HyperX",
        href: "/products/hyperx-pulsefire-haste2",
        thumbnail: "/icons/mouse.png",
        badge: "Sale",
        productCode: "MS07006",
        price: 1_490_000,
        originalPrice: 1_890_000,
        rating: 4.6,
        reviewCount: 119,
        stockStatus: "in-stock",
      },
    ],
  },
];
